from building import *
import rtconfig

# get current directory
cwd     = GetCurrentDir()
# The set of source files associated with this SConscript file.
src     = Glob('omv/img/*.c')
src    += Glob('omv/nn/*.c')
src    += Glob('omv/py/py_helper.c')
src    += Glob('omv/py/py_sensor.c')
src    += Glob('omv/py/py_time.c')
src    += Glob('omv/py/py_image.c')
src    += Glob('omv/py/py_gif.c')
src    += Glob('omv/py/py_mjpeg.c')
src    += Glob('omv/py/py_nn.c')

src    += Glob('omv/array.c')
src    += Glob('omv/fb_alloc.c')
src    += Glob('omv/ff_wrapper.c')
src    += Glob('omv/framebuffer.c')
src    += Glob('omv/ini.c')
src    += Glob('omv/mutex.c')
src    += Glob('omv/trace.c')
src    += Glob('omv/umm_malloc.c')
src    += Glob('omv/usbdbg.c')
src    += Glob('omv/wifidbg.c')
src    += Glob('omv/xalloc.c')
src    += Glob('omv/pendsv.c')

path    = [cwd + '/omv']
path   += [cwd + '/omv/img']
path   += [cwd + '/omv/nn']
path   += [cwd + '/omv/py']
path   += [cwd + '/cmsis/include']
LOCAL_CCFLAGS = ''

if rtconfig.CROSS_TOOL == 'gcc':
    LOCAL_CCFLAGS += ' -std=c99'
elif rtconfig.CROSS_TOOL == 'keil':
    LOCAL_CCFLAGS += ' --c99 --gnu'

group = DefineGroup('OMV', src, depend = ['NXP_USING_OPENMV'], CPPPATH = path, LOCAL_CCFLAGS = LOCAL_CCFLAGS)

Return('group')
